<?php

namespace Plugin\MemProduct\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\MemProduct\Entity\ProductSort;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ProductSortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSortRepository extends AbstractRepository
{
    /**
     * ProductSortRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ProductSort::class);
    }

    /**
     * @param int $id
     *
     * @return null|Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
